// The client viewer's HTML, generated by `npm run build:single` as base64 (a raw HTML string would contain
// "</script>" and break the editor's own inlined script). Absent in dev builds, where export is disabled.
const found = import.meta.glob('../generated/client-template.ts', { eager: true }) as Record<string, { default: string }>;

export function getClientTemplate(): string | null {
  const mod = Object.values(found)[0];
  if (!mod) return null;
  const bytes = Uint8Array.from(atob(mod.default), (c) => c.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}
